apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "machine-learning-lab.fullname" . }}-minio-data
  labels:
    {{- include "machine-learning-lab.labels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "minio"
spec:
  accessModes: [ "ReadWriteOnce" ]
  {{- if .Values.integratedMinio.storageClassName }}
  storageClassName: {{ .Values.integratedMinio.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.integratedMinio.storageSize }}
