{{- if .Values.integratedMinio.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "machine-learning-lab.fullname" . }}-minio
  labels:
    {{- include "machine-learning-lab.labels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "minio"
spec:
  type: {{ .Values.integratedMinio.service.type }}
  ports:
    - port: {{ .Values.integratedMinio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "machine-learning-lab.selectorLabels" . | nindent 4 }}
    ctxy.deploymentType: "core"
    ctxy.deploymentName: "minio"
{{- end }}
