on: workflow_dispatch
name: 'Build and Test ML Lab'
jobs:
  testbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Cache maven modules
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-modules
      with:
        # maven cache files are stored in `~/.m2` on Linux/macOS
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with: 
        path: webapp/node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - name: Create network
      run: docker network create lab-core
    - name: Run container build with tests
      run: /bin/bash container-build.sh
